### ISSUE TITLE
Failed to parse sourcemap when files in /imports

### ISSUE THREAD

**Issue by hyperh** [hyperh/mantra-skeleton#2]
https://forums.meteor.com/t/failed-to-parse-sourcemap-issue-with-meteor-1-3/18542/24

**Comment by adrianmcli** [comment]
This seems to be a bit more enlightening: https://github.com/meteor/meteor/issues/7206

**Comment by adrianmcli** [comment]
There are a couple other issues on the official meteor GH repo that talk about this particular error. It's often some kind of SCSS statement that trips it up. I'm not sure what that could be in our repo though.

If you're curious, search "failed to parse sourcemap" on the meteor repo issues.

**Comment by hyperh** [comment]
I was able to move the user module to imports with no issues. The issue must be in core. You can checkout the branch `imports-folder`.
