### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by adrianmcli** [hyperh/mantra-skeleton#3]
App still builds, but this error shows up:

```
Unable to resolve some modules:

  "meteor-auth" in /Users/liadrian/Dev/mantra-skeleton/client/modules/core/routes.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-auth
```

Running `meteor npm install --save meteor-auth` seems to fail for some reason.

**Comment by adrianmcli** [comment]
This is also causing the following runtime error (and hence preventing app from loading):

![screen shot 2016-07-02 at 8 51 10 pm](https://cloud.githubusercontent.com/assets/943555/16540664/ce908c46-4096-11e6-933a-336327fa5aaa.png)

**Comment by hyperh** [comment]
Did you `npm install`?

**Comment by hyperh** [comment]
Ah I see I forgot to do `npm --save install`

**Comment by hyperh** [comment]
Closed by https://github.com/hyperh/mantra-skeleton/pull/4

**Comment by adrianmcli** [comment]
@hyperh I think it's a good idea (once in a while) to do a wipe + pull from GH repo just to make sure all the dependencies are listed.
